GLOB_INCLUDE : 
  - "src/"

BUILD_OUTPUT : "~/BUILD_OUTPUT/"

BUILD_TARGET :
  - target_test
  - target_foo

target_test : 
  NAME : test
  TYPE : shared
  DEPS :
    - REPO : git@github.com:wenjie-he/invention.git
      BRANCH : main
  SOURCE :
    - "src/test.cpp"
  INCLUDE :
    - "src/"
  FLAGS :
    - "-g"
    - "-fPIC"
    - "-W"
    - "-Wall"
  LIBS :
    - "z"
    - "pthread"
    - "ssl"

target_foo : 
  NAME : foo
  TYPE : static
  DEPS : 
    - REPO : git@github.com:wenjie-he/top_track.git
      BRANCH : master
  SOURCE :
    - "src/foo.cpp"
  INCLUDE :
    - "src/"
  FLAGS :
    - "-g"
    - "-fPIC"
    - "-W"
    - "-Wall"
